local max_usr = ui.reference("MISC", "Settings", "sv_maxusrcmdprocessticks")
local dt_lua_enable = ui.new_checkbox("rage", "other", "Improved double tap")
client.set_event_callback("run_command", function() if not ui.get(dt_lua_enable) then ui.set(max_usr, 16) return end ui.set(max_usr, 20) end)

local dt_lua_watermark_label = ui.new_label("lua", "a", "[IDT] Custom watermark")
local dt_lua_watermark_color = ui.new_color_picker("lua", "a", "clr", 46, 204, 113, 255)
local dt_lua_watermark_text = ui.new_textbox("lua", "a", "txt")
ui.set(dt_lua_watermark_text, "Salvators left nut")
client.set_event_callback("paint_ui", function()
    local h,w = client.screen_size()
    local maintext = string.format("skeet.cc [%s] %s | %s | %stick | %sms", entity.get_prop(entity.get_player_resource(), "m_szClan", entity.get_local_player()) ,ui.get(dt_lua_watermark_text), entity.get_player_name(entity.get_local_player()), 1/globals.tickinterval(), math.floor(client.latency()*1000+0.5))
    local textx, texty = renderer.measure_text(nil, maintext)
    local r,g,b,a = ui.get(dt_lua_watermark_color)
    renderer.rectangle(h-10-textx, w/100, h-15-textx, 20, 25, 25, 25, 255)
    renderer.rectangle(h-10-textx, w/100, h-15-textx, 1, r,g,b,a)
    renderer.text(h-10-textx+5, w/100+3, 255, 255, 255, 255, nil, 0, maintext)
end)